name: Create Release

on:
  workflow_dispatch

jobs:
  create-tag:
    name: "Create tag from package.json"
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.create-tag.outputs.version }}
      tag: ${{ steps.create-tag.outputs.tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Git tag
        id: create-tag
        run: |
          version="$(jq -r '.version' package.json)"
          tag="v$version"
          git tag $tag
          git push origin $tag
          echo "version=$version" >> "$GITHUB_OUTPUT"
          echo "tag=$tag" >> "$GITHUB_OUTPUT"

  github-release:
    environment: "Production"
    needs:
      - create-tag
    name: "Create GitHub release"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create changelog
        id: changelog
        uses: loopwerk/tag-changelog@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config_file: .github/tag-changelog.cjs

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{needs.create-tag.outputs.tag}}
          name: Release ${{needs.create-tag.outputs.tag}}
          body: ${{ steps.changelog.outputs.changes }}

  build-from-source:
    environment: "Production"
    needs:
      - create-tag
    name: "Build extension"
    runs-on: ubuntu-latest
    permissions:
      contents: write

    strategy:
      matrix:
        browser: ['chromium', 'firefox']

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build for ${{ matrix.browser }}
        run: npm run build:${{ matrix.browser }}

      - name: Compress build
        run: cd ./dist && zip -r ../emojis-table-${{ matrix.browser }}-${{needs.create-tag.outputs.tag}}.zip .

      - name: Upload Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{needs.create-tag.outputs.tag}} emojis-table-${{ matrix.browser }}-${{needs.create-tag.outputs.tag}}.zip
